version: '3.8'

services:
  postgres:
    container_name: spring-reactive
    image: postgres:latest
    environment:
      POSTGRES_DB: spring_webflux_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "4242:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: